spring:
  application:
    name: ILearnApp
  datasource:
    url: jdbc:postgresql://localhost:5051/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  thymeleaf:
#    check-template: true
#    check-template-location: true
#    cache: false
#    enabled: true
#    encoding: UTF-8
#    mode: HTML
#    prefix: classpath:/templates/
#    suffix: .html

server:
  port: 9090

